name: Wipe all clusters and apps

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    name: Wipe all clusters and apps on dev
    steps:
    - uses: realm/ci-actions/mdb-realm/deleteAllClusters@310eecac34e016ffc36d41b7607e97c39c4d70e8
      name: "on realm.dev"
      with:
        realmUrl: ${{ secrets.REALM_BASE_URL }}
        atlasUrl: ${{ secrets.ATLAS_BASE_URL }}
        projectId: ${{ secrets.ATLAS_PROJECT_ID }}
        apiKey: ${{ secrets.ATLAS_PUBLIC_API_KEY }}
        privateApiKey: ${{ secrets.ATLAS_PRIVATE_API_KEY }}
    - uses: realm/ci-actions/mdb-realm/deleteAllClusters@e7b65d7d587e1abc358968d7ff816cc0163906d2
      name: "on realm.qa"
      with:
        realmUrl: ${{ secrets.REALM_QA_BASE_URL }}
        atlasUrl: ${{ secrets.ATLAS_QA_BASE_URL }}
        projectId: ${{ secrets.ATLAS_QA_PROJECT_ID }}
        apiKey: ${{ secrets.ATLAS_QA_PUBLIC_API_KEY }}
        privateApiKey: ${{ secrets.ATLAS_QA_PRIVATE_API_KEY }}
