name: Wipe all clusters and apps

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    name: Wipe all clusters and apps on dev
    steps:
    - uses: realm/ci-actions/mdb-realm/deleteAllClusters@3d95b9f473d06ef0f56e1a5d8c5981743dc4fed9
      name: "on realm.dev"
      with:
        realmUrl: ${{ secrets.REALM_BASE_URL }}
        atlasUrl: ${{ secrets.ATLAS_BASE_URL }}
        projectId: ${{ secrets.ATLAS_PROJECT_ID }}
        apiKey: ${{ secrets.ATLAS_PUBLIC_API_KEY }}
        privateApiKey: ${{ secrets.ATLAS_PRIVATE_API_KEY }}
    - uses: realm/ci-actions/mdb-realm/deleteAllClusters@3d95b9f473d06ef0f56e1a5d8c5981743dc4fed9
      name: "on realm.qa"
      with:
        realmUrl: ${{ secrets.REALM_QA_BASE_URL }}
        atlasUrl: ${{ secrets.ATLAS_QA_BASE_URL }}
        projectId: ${{ secrets.ATLAS_QA_PROJECT_ID }}
        apiKey: ${{ secrets.ATLAS_QA_PUBLIC_API_KEY }}
        privateApiKey: ${{ secrets.ATLAS_QA_PRIVATE_API_KEY }}
