# This workflow builds the JSDocs but does not publish them.
# This runs on pull requests, so that any errors in the JSDoc will trigger
#Â a build failure, but we do not want to publish the results to the live site.

name: JSDoc Build
on:
  pull_request:
    paths:
      # documentation
      - "docs/**"
      - "*.md"
      # changes to this workflow
      # seems there is no way to get this easily yet https://github.com/actions/runner/issues/853
      - ".github/workflows/jsdoc.yml"

env:
  REALM_DISABLE_ANALYTICS: 1
jobs:
  jsdoc:
    name: JSDoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - name: Install root package dependencies
        run: npm ci --ignore-scripts
      - name: Run JSDoc documentation build
        run: npm run jsdoc
