name: Linting (Pull Request)
on: pull_request
env:
  REALM_DISABLE_ANALYTICS: 1
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # Install the root package
      - name: Install root package dependencies
        run: npm ci
      - name: Run linting of subpackages
        run: npm run turbo:lint
      - name: Run linting of C++ code
        run: npm run lint:cpp
