name: Linting (Pull Request)
on: pull_request
env:
  REALM_DISABLE_ANALYTICS: 1
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install npm v7
        run: npm install -g npm@8
      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - name: Install root package dependencies
        run: npm ci --ignore-scripts
      - name: Install subpackages dependencies
        run: npm run lerna:bootstrap
      - name: Run linting of subpackages
        run: npm run lerna:lint -- --no-bail --concurrency 1 --stream --no-prefix
      - name: Run linting of C++ code
        run: npm run lint:cpp
