name: Testing Realm Web (Pull Request)

on:
  push:
    paths:
      # Only run when the PR makes changes to the packages
      - 'packages/**'

jobs:
  test-build-and-publish:
    name: Test, lint and build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      # Install the root package
      - run: npm ci
      # Bootstrap lerna sub-packages
      - run: npx lerna bootstrap
      # Lint, build and test the package
      - run: npm run lint
        working-directory: packages/realm-web
      - run: npm run build
        working-directory: packages/realm-web
      - run: npm test
        working-directory: packages/realm-web
      # Login with the Docker CLI to enable the integration test harness to pull the mongodb-realm-test-server
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: realm-ci
          password: ${{ secrets.REALM_CI_GITHUB_API_KEY }}
      - run: npm run test:github
        working-directory: packages/realm-web-integration-tests
        env:
          MONGODB_REALM_TEST_SERVER: latest
