name: Testing Realm React (Pull Request)

env:
  REALM_DISABLE_ANALYTICS: 1

on:
  pull_request:
    paths:
      - "*"
      - "lib/**"
      - "src/**"
      - "types/**"
      - "react-native/**"
      - "vendor/**"
      # Integration tests
      - "integration-tests/**"
      - "packages/realm-react/**"
      - ".github/workflows/pr-realm-react.yml"
      # No need to run when updating documentation
      - "!**.md"
jobs:
  job:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # Caches
      - uses: actions/cache@v2
        name: cached node_modules
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ github.job }}-${{ hashFiles('package-lock.json') }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: realm-react

      - name: Prepend ccache executables to the PATH
        run: echo PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV

      - name: Install realm node dependencies
        run: npm ci

      - name: Prebuild release binary
        run: npx prebuild

      - name: Build realm react
        working-directory: packages/realm-react
        run: npm run build

      - name: Run tests
        working-directory: packages/realm-react
        run: npm run test
