name: Publish Realm React

on:
  push:
    tags:
      - realm-react-v*
env:
  REALM_DISABLE_ANALYTICS: 1

jobs:
  test-build-and-publish:
    name: Test, build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install npm v7
        run: npm install -g npm@7
      # Caches
      - uses: actions/cache@v2
        name: cached node_modules
        id: cache-node-modules
        with:
          path: node_modules
          key: node-modules-${{ github.job }}-${{ hashFiles('package-lock.json') }}
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
      - name: Prepend ccache executables to the PATH
        run: echo PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH" >> $GITHUB_ENV

      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - name: Install realm node dependencies
        run: npm ci --ignore-scripts

      - name: Install common realm
        run: npx lerna bootstrap --scope @realm.io/common

      - name: Prebuild release binary
        run: npx prebuild

      - name: Pack and distribute realm to realm react
        run: npm pack && mv realm*.tgz packages/realm-react

      - name: Install node dependencies
        working-directory: packages/realm-react
        run: npm install realm*.tgz

      - name: Build realm react
        working-directory: packages/realm-react
        run: npm run build

      - name: Run tests
        working-directory: packages/realm-react
        run: npm run test
      # Publish the package
      - run: npm publish
        working-directory: packages/realm-react
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
