name: Publish Realm Web

on:
  push:
    tags:
      - realm-web-v*
env:
  REALM_DISABLE_ANALYTICS: 1

jobs:
  test-build-and-publish:
    name: Test, build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      # Install the root package (--ignore-scripts to avoid downloading or building the native module)
      - run: npm ci
      # Test the package
      - run: npm test
        working-directory: packages/realm-web
      # Publish the package
      - run: npm publish
        working-directory: packages/realm-web
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
