name: Start BaaS test server (test)

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: BaaS branch to use when starting the server
        default: master
      githash:
        type: string
        description: Specific githash to use when starting the server (this is used instead of branch if provided)

jobs:
  server:
    name: Run test server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Start BaaS test server
        id: baas
        uses: ./.github/actions/baas-test-server
        with:
          baasaas-key: ${{ secrets.BAASAAS_KEY }}
          branch: ${{ inputs.branch }}
          githash: ${{ inputs.githash }}
      - name: Perform a request to the server
        run: curl ${{ steps.baas.outputs.baas-url }}/api/private/v1.0/version
